import turtle
wn = turtle.Screen()
wn.bgcolor("light green")
alex = turtle.Turtle()
alex.shape("turtle")
alex.color("blue")
alex.pensize(3)
alex.stamp()
for i in range(12):
    alex.penup()
    alex.forward(200)
    alex.stamp()
    alex.forward(-30)
    alex.pendown()
    alex.forward(10)
    alex.penup()
    alex.forward(-180)
    alex.left(30)

wn.mainloop()
